apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: location-store
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.default.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: credentialsecrets
      key: redis-password
  - name: actorStateStore
    value: "false"
  - name: keyPrefix
    value: none
auth:
  secretStore: kubernetes