apiVersion: apps/v1
kind: Deployment
metadata:
  name: allactors
  labels:
    app: allactors
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: allactors
  template:
    metadata:
      labels:
        app: allactors
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "allactors"
        dapr.io/port: "3000"
        dapr.io/sidecar-liveness-probe-delay-seconds: "20"
        dapr.io/sidecar-liveness-probe-timeout-seconds: "2"
    spec:
      serviceAccountName: default
      containers:
      - name: allactors
        image: "833200667006.dkr.ecr.eu-west-1.amazonaws.com/actors.allactors:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: ASPNETCORE_Kestrel__Endpoints__Http__Url
            value: "http://+:3000"