apiVersion: v1
kind: Service
metadata:
  name: location-api
  labels:
    app: location-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: location-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-api
  labels:
    app: location-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: location-api
  template:
    metadata:
      labels:
        app: location-api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "location-api"
        dapr.io/port: "3000"
        dapr.io/sidecar-liveness-probe-delay-seconds: "20"
        dapr.io/sidecar-liveness-probe-timeout-seconds: "2"
    spec:
      serviceAccountName: default
      containers:
      - name: flow-normalization
        image: "833200667006.dkr.ecr.eu-west-1.amazonaws.com/api.locationapi:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: ASPNETCORE_Kestrel__Endpoints__Http__Url
            value: "http://+:3000"