apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "application-ingress"
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    # alb.ingress.kubernetes.io/certificate-arn: {{ .Values.acm }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/scheme: internet-facing
    # external-dns.alpha.kubernetes.io/hostname: {{ .Values.normalization.url }} # give your domain name here
  labels:
    app: application-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /character
            backend:
              serviceName: "character-api"
              servicePort: 80
          - path: /location
            backend:
              serviceName: "location-api"
              servicePort: 80
          - path: /quest
            backend:
              serviceName: "quest-api"
              servicePort: 80